# Generated by Django 4.2.4 on 2023-08-15 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('umumiy', models.FloatField()),
                ('vaqt', models.DateTimeField(default=datetime.datetime(2023, 8, 15, 9, 42, 0, 248794))),
            ],
        ),
    ]
