# Generated by Django 4.2.4 on 2023-08-15 04:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 9, 55, 36, 666765)),
        ),
    ]
