# Generated by Django 4.2.4 on 2023-08-16 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0002_alter_savat_vaqt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savat',
            old_name='umumiy',
            new_name='umumiy_summa',
        ),
        migrations.AlterField(
            model_name='savat',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 8, 12, 21, 328783)),
        ),
    ]
