# Generated by Django 4.2.4 on 2023-08-16 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0003_rename_umumiy_savat_umumiy_summa_alter_savat_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 9, 16, 43, 504972)),
        ),
    ]
