# Generated by Django 4.2.4 on 2023-08-17 03:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_alter_mahsulot_narx_tanlangan'),
        ('userapp', '0004_profil_email_profil_uy_manzili'),
        ('buyurtma', '0005_alter_savat_vaqt'),
    ]

    operations = [
        migrations.AddField(
            model_name='savat',
            name='mahsulot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asosiy.mahsulot'),
        ),
        migrations.AddField(
            model_name='savat',
            name='profil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.profil'),
        ),
        migrations.AlterField(
            model_name='savat',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 8, 17, 13, 975760)),
        ),
    ]
