# Generated by Django 4.2.4 on 2023-08-17 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0006_savat_mahsulot_savat_profil_alter_savat_vaqt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 8, 21, 13, 679361)),
        ),
    ]
