# Generated by Django 4.2.4 on 2023-08-17 04:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_profil_email_profil_uy_manzili'),
        ('buyurtma', '0007_alter_savat_vaqt'),
    ]

    operations = [
        migrations.AddField(
            model_name='savat',
            name='arxivda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savat',
            name='vaqt',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 9, 55, 45, 510686)),
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('manzil', models.CharField(max_length=300)),
                ('zipcode', models.CharField(max_length=7)),
                ('summa', models.IntegerField()),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.profil')),
                ('savatlar', models.ManyToManyField(to='buyurtma.savat')),
            ],
        ),
    ]
