# Generated by Django 4.2.4 on 2023-08-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_profil_ism'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='rasm',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
