# Generated by Django 4.2.4 on 2023-08-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_profil_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='uy_manzili',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
