# Generated by Django 4.2.4 on 2023-08-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_profil_email_profil_uy_manzili'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='tel',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
